from django.urls import path
from . import views

urlpatterns = [
    path("health/", views.health),
    path("auth/register/", views.register),
    path("auth/login/", views.login),
    path("auth/forgot-password/", views.forgot_password),
    path("auth/reset-password/", views.reset_password),
    path("auth/google/", views.google_login),
    path("auth/logout/", views.logout),
    path("auth/me/", views.me),
    path("auth/profile/", views.profile),
    path("admin/users/", views.admin_users),
    path("admin/subscriptions/", views.subscriptions),
    path("admin/plans/", views.admin_plans),
    path("admin/coupons/", views.admin_coupons),
    path("admin/payment-methods/", views.admin_payment_methods),
    path("payments/", views.payments),
    path("payments/paymob/checkout/", views.paymob_checkout),
    path("payments/paymob/webhook/", views.paymob_webhook),
    path("notifications/", views.notifications),
    path("support-chat/", views.support_chat),
    path("support-chat/<str:message_id>/attachment/", views.support_chat_attachment),
    path("chat-presence/", views.chat_presence),
    path("notes/", views.notes),
    path("notes/<str:note_id>/", views.note_detail),
    path("platforms/", views.platforms),
    path("platforms/<str:platform_id>/", views.platform_detail),
    path("earnings/", views.earnings),
    path("earnings/export/", views.export_earnings_csv),
    path("earnings/import/", views.import_earnings_csv),
    path("earnings/<str:earning_id>/", views.earning_detail),
    path("goals/", views.income_goals),
    path("dashboard/preferences/", views.dashboard_preferences),
    path("dashboard/", views.dashboard),
]
