from django.urls import path
from . import views
from . import jobs as job_views
from . import applications as application_views
from . import application_workspace as application_workspace_views
from . import resumes as resume_views

urlpatterns = [
    path("health/", views.health),
    path("auth/register/", views.register),
    path("auth/login/", views.login),
    path("auth/forgot-password/", views.forgot_password),
    path("auth/reset-password/", views.reset_password),
    path("auth/google/", views.google_login),
    path("auth/logout/", views.logout),
    path("auth/me/", views.me),
    path("auth/profile/", views.profile),
    path("admin/users/", views.admin_users),
    path("admin/subscriptions/", views.subscriptions),
    path("admin/plans/", views.admin_plans),
    path("admin/coupons/", views.admin_coupons),
    path("admin/payment-methods/", views.admin_payment_methods),
    path("payments/", views.payments),
    path("payments/paymob/checkout/", views.paymob_checkout),
    path("payments/paymob/webhook/", views.paymob_webhook),
    path("notifications/", views.notifications),
    path("support-chat/", views.support_chat),
    path("support-chat/<str:message_id>/attachment/", views.support_chat_attachment),
    path("chat-presence/", views.chat_presence),
    path("jobs/", job_views.jobs_feed),
    path("resumes/", resume_views.resumes),
    path("resumes/import/", resume_views.resume_import),
    path("resumes/<str:resume_id>/", resume_views.resume_detail),
    path("resumes/<str:resume_id>/readiness/", resume_views.resume_readiness),
    path("resumes/<str:resume_id>/duplicate/", resume_views.resume_duplicate),
    path("resumes/<str:resume_id>/versions/", resume_views.resume_versions),
    path("resumes/<str:resume_id>/versions/<str:version_id>/restore/", resume_views.resume_restore_version),
    path("resumes/<str:resume_id>/analyze/", resume_views.resume_analyze),
    path("resumes/<str:resume_id>/job-matches/", resume_views.resume_job_matches),
    path("cover-letters/", resume_views.cover_letters),
    path("cover-letters/<str:cover_letter_id>/", resume_views.cover_letter_detail),
    path("applications/", application_views.applications),
    path("applications/stats/", application_views.application_stats),
    path("applications/agenda/", application_workspace_views.application_agenda),
    path("applications/analytics/", application_workspace_views.application_analytics),
    path("applications/<str:application_id>/materials/", resume_views.application_materials),
    path("applications/<str:application_id>/", application_views.application_detail),
    path("applications/<str:application_id>/status/", application_views.application_status),
    path("applications/<str:application_id>/events/", application_views.application_events),
    path("applications/<str:application_id>/tasks/", application_workspace_views.application_tasks),
    path("applications/<str:application_id>/tasks/<str:task_id>/", application_workspace_views.application_task_detail),
    path("applications/<str:application_id>/interviews/", application_workspace_views.application_interviews),
    path("applications/<str:application_id>/interviews/<str:interview_id>/", application_workspace_views.application_interview_detail),
    path("applications/<str:application_id>/documents/", application_workspace_views.application_documents),
    path("applications/<str:application_id>/documents/<str:document_id>/", application_workspace_views.application_document_detail),
    path("notes/", views.notes),
    path("notes/<str:note_id>/attachments/", views.note_attachments),
    path("notes/<str:note_id>/attachments/<str:attachment_id>/", views.note_attachment),
    path("notes/<str:note_id>/", views.note_detail),
    path("platforms/", views.platforms),
    path("platforms/<str:platform_id>/", views.platform_detail),
    path("earnings/", views.earnings),
    path("earnings/export/", views.export_earnings_csv),
    path("earnings/import/", views.import_earnings_csv),
    path("earnings/<str:earning_id>/", views.earning_detail),
    path("goals/", views.income_goals),
    path("dashboard/preferences/", views.dashboard_preferences),
    path("dashboard/", views.dashboard),
]
