services:
  mongo:
    image: mongo:8.0
    container_name: revnivo-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - revnivo_mongo_data:/data/db

volumes:
  revnivo_mongo_data:
