import { Button, Pagination, TextInput, Textarea } from 'flowbite-react'
import { FileText, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import EmptyState from '../components/EmptyState'
import Loading from '../components/Loading'
import Modal from '../components/Modal'
import api from '../services/api'

const cairoDate = (value) => value ? new Date(value).toLocaleString('en-EG', { timeZone: 'Africa/Cairo' }) : ''

export default function Notes() {
  const [items, setItems] = useState([]); const [pagination, setPagination] = useState({ page: 1, pages: 1 }); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [form, setForm] = useState({ title: '', content: '' }); const [editing, setEditing] = useState(null); const [modal, setModal] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const load = async (nextPage = page) => { setLoading(true); try { const { data } = await api.get('/notes/', { params: { page: nextPage, search } }); setItems(data.results); setPagination(data.pagination) } catch (err) { setError(err.response?.data?.detail || 'Could not load notes.') } finally { setLoading(false) } }
  useEffect(() => { load(page) }, [page, search])
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { if (editing) await api.patch(`/notes/${editing.id}/`, form); else await api.post('/notes/', form); setForm({ title: '', content: '' }); setEditing(null); setModal(false); setPage(1); await load(1) } catch (err) { setError(err.response?.data?.detail || 'Could not save note.') } finally { setSaving(false) } }
  const remove = async (note) => { if (!window.confirm('Delete this note?')) return; await api.delete(`/notes/${note.id}/`); await load(page) }
  if (loading && !items.length) return <Loading label="Loading notes..."/>
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-[#16843d]">Workspace</p><h1 className="mt-1 text-3xl font-black dark:text-white">Notes</h1><p className="mt-1 text-sm text-slate-500">Keep useful context beside your earnings.</p></div><Button color="success" onClick={() => { setEditing(null); setForm({ title: '', content: '' }); setModal(true) }}><Plus size={18}/>Add note</Button></div>{error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<div className="card overflow-hidden"><div className="border-b border-slate-200 p-4"><TextInput icon={Search} value={search} onChange={(event) => { setPage(1); setSearch(event.target.value) }} placeholder="Search notes..."/>{items.length ? <div className="divide-y divide-slate-100 dark:divide-[#45484d]">{items.map((note) => <article key={note.id} className="flex items-start gap-4 p-5"><div className="rounded-xl bg-[#e8f8ed] p-2 text-[#16843d]"><FileText size={18}/></div><div className="min-w-0 flex-1"><h2 className="font-bold dark:text-white">{note.title || 'Untitled note'}</h2><p className="mt-1 whitespace-pre-wrap text-sm text-slate-600 dark:text-slate-300">{note.content}</p><p className="mt-3 text-xs text-slate-400">Created {cairoDate(note.created_at)}</p></div><button className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" onClick={() => { setEditing(note); setForm({ title: note.title, content: note.content }); setModal(true) }}><Pencil size={17}/></button><button className="rounded-lg p-2 text-rose-500 hover:bg-rose-50" onClick={() => remove(note)}><Trash2 size={17}/></button></article>)}</div> : <div className="p-5"><EmptyState title="No notes yet" text="Create a note to keep useful context beside your earnings."/></div>}</div>{pagination.pages > 1 && <div className="flex justify-center border-t border-slate-200 p-3"><Pagination currentPage={page} totalPages={pagination.pages} onPageChange={setPage}/></div>}</div><Modal open={modal} onClose={() => setModal(false)} title={editing ? 'Edit note' : 'Add note'}><form onSubmit={submit} className="space-y-4"><div><label className="label">Title</label><input className="input" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })}/></div><div><label className="label">Note</label><Textarea required rows={7} value={form.content} onChange={(event) => setForm({ ...form, content: event.target.value })}/></div><div className="flex justify-end gap-2"><Button color="light" type="button" onClick={() => setModal(false)}>Cancel</Button><Button color="success" type="submit" disabled={saving}>{saving ? 'Saving...' : 'Save note'}</Button></div></form></Modal></div>
}
